### ISSUE TITLE
How to deserialize dat files?

### ISSUE THREAD

**Issue by bigfoxtail** [brave/adblock-rust#103]
I want to deserialize the dat file to get the list, but the code doesn't provide an interface.
What should I do?
thanks！

**Comment by antonok-edm** [comment]
@bigfoxtail the lists themselves are all described in [src/filter_lists](https://github.com/brave/adblock-rust/tree/master/src/filter_lists) and I'd recommend reading through those instead if you're interested in seeing the rules themselves. The DAT simply provides an efficient packaging mechanism so that browsers don't have to parse a whole bunch of filter rules at runtime.

If you'd like to deserialize a DAT into an actual adblocking engine you can use [`Engine::deserialize`](https://github.com/brave/adblock-rust/blob/a3e35df90b24702125bf0e174dbf71cbb51813f2/src/engine.rs#L50).
