### ISSUE TITLE
Cosmetic filtering subsystem documentation

### ISSUE THREAD

**Issue by naifmeh** [brave/adblock-rust#152]
Rules with statically typed attributes don't seem to be handled by the library. For instance, div[class='a-class'] is equivalent to div.a-class. However, in the code below and unless I am mistaking, the "_hidden_class_id_selectors_" method should return a non empty vector corresponding to the first rule in the set.

The "_hidden_class_id_selectors_" seems to be using the masks set in the CosmeticFilter object related to the rule ("div[class='a-class']") , however, printing it shows no masks being set for it, which causes the CosmeticFilterCache to store the rule in _misc_generic_selectors_ which is in turn ignored by the method "_hidden_class_id_selectors_".

```rust
let rules = [
            String::from("##div[class='a-class']"),
            String::from("##div[class*=\"Ads\"]"),
            String::from("##.a-class")
        ];
// For debugging purpose
rules.iter().for_each(|rule| {
    let cf: CosmeticFilter = CosmeticFilter::parse(rule, false).unwrap();
    println!("{:?}", cf);
});
//----

let blocker = Engine::from_rules_debug(&rules, FilterFormat::Standard)
let example_class_report = blocker.hidden_class_id_selectors(&["div.a-class".into()], &[], &HashSet::default());

println!("Report for a-class: {:?}", example_class_report);
```

Are these rules supported in the current version ? If yes, how are they supposed to be used ?
Similarly, are composed rules (for example, "div#ads > .advertisement") also handled ?
Some additional documentation/examples should be added regarding the usage of cosmetic rules.
 
Please let me know if my facts are wrong as I am getting started with the Rust language/library.

**Comment by antonok-edm** [comment]
There's actually two separate APIs that need to be considered when using `adblock-rust` for cosmetic filtering. One is `hidden_class_id_selectors` as you've discovered; the other is `url_cosmetic_resources`.

Generic class/id rules are by far the most common type of cosmetic filtering rule, and they apply to all sites. Rather than injecting _all_ of these rules onto every page, which would blow up memory usage, we only inject rules based on classes and ids that actually appear on the page (in practice, we use a `MutationObserver` to identify those elements). We can include rules like `.a-class div#ads > .advertisement`, keyed by the `.a-class` selector, since we know that this rule cannot possibly apply unless there is an `.a-class` element on the page.

Any rules that don't directly start with a class or id selector would have to be returned by `url_cosmetic_resources`, which should be called as soon as a page navigation is committed. That allows you to get the set of rules that apply per-site (e.g. `example.com##.a-class`), as well as any that are generic and more complex (e.g. `div[class*="Ads"]`). That last category is always injected into every page, and makes up a relatively small number of rules in practice.

**Comment by antonok-edm** [comment]
Please let me know if you have more questions; I'll leave this issue open to track better documentation on the cosmetic rules handling.

**Comment by naifmeh** [comment]
@antonok-edm : Thank you for your quick answer !
I'm noticing my original comment is lacking precision (I edited it) as I was willing to mention the case of _url_cosmetic_resources_ as well. Your answer makes it clearer as to how both APIs should be used. 

I do have one more question :
* If the library was to be used as standalone, how would one be able to match selectors to load cosmetic filters the same way the _check_network_urls_ matches network rules ? To take the previous example, is there a method where I could input "div.a-class" and know whether it is matched by a filter in the given set of rules ?

If this is possible, I think the repo would really benefit from an example.

**Comment by ArniDagur** [comment]
I agree. I used this library to introduce network blocking in [qutebrowser](https://github.com/qutebrowser/qutebrowser), but I'm unsure how I would use it to implement cosmetic blocking. I tried reading the C++ code in Brave Browser, but I couldn't get a grasp of what was going on.

**Comment by antonok-edm** [comment]
@naifmeh

> * If the library was to be used as standalone, how would one be able to match selectors from a page to cosmetic rules the same way the _check_network_urls_ matches network rules ? To take the previous example, is there a method where I could input "div.a-class" and know whether it is matched by a filter in the given set of rules ?

Cosmetic blocking is less precise than network blocking since it's built around bulk CSS application rather than for discrete network requests. For that reason it's not trivial to get a concrete answer to "does this single element match a cosmetic filter." But roughly, first you'd want to call `url_cosmetic_resources`, of which three fields are relevant: `hide_selectors`, `style_selectors`, and `exceptions`. Then you'll want to gather all of the CSS classes and ids that occur on the page, and call `hidden_class_id_selectors`, being sure to pass the `exceptions` as the third argument.
- `hide_selectors` is a list of CSS selectors to which `display: none !important` should be applied.
- The result from `hidden_class_id_selectors` is another list of simple CSS selectors to which `display: none !important` should be applied.
- `style_selectors` maps CSS selectors on the page to corresponding rules other than `display: none !important`.

In practice, these sets will identify a decent number of selectors that do not actually apply to the page, since it becomes computationally expensive to filter them down further. However, the system is designed to guarantee that loading all of the returned rules will _not_ cause an element to be hidden when it shouldn't be.

It's also tough to answer whether or not a particular `div.a-class` should be hidden without some notion of CSS semantics and HTML document context. For example, if you have rules like `##div.a-class.b-class`, then you can't confidently answer without more information about the element in question. If you have rules like `##.parent div.a-class`, then the answer may ultimately depend on the entire hierarchy of HTML parents up to the root document.

I doubt it's the answer you were hoping for, but I think you'll want to end up embedding some kind of HTML/CSS engine.

> If this is possible, I think the repo would really benefit from an example.

Noted :smile:

**Comment by antonok-edm** [comment]
@ArniDagur I just saw that https://github.com/qutebrowser/qutebrowser/pull/5317 got merged, congratulations on that! Will work on documentation more, but in the meantime please feel free to reach out if something's unclear.

**Comment by naifmeh** [comment]
@antonok-edm Thank you for the precisions :)

**Comment by antonok-edm** [comment]
I _think_ https://github.com/brave/adblock-rust/commit/445b633d94e4139cce94a154acf530f9a449f945 should be sufficient, but feel free to reopen or make a new issue if something seems missing!
