### ISSUE TITLE
Ads in all youtube videos.

### ISSUE THREAD

**Issue by axeldaniel** [brave/adblock-rust#303]
Version
[Version 1.56.20 Chromium: 115.0.5790.171 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by antonok-edm** [comment]
@axeldaniel @robd003 @n33pm this is more of an issue with Brave Browser than adblock-rust, but FWIW it should have been fixed by a component update (`Brave Ad Block Resources Library - Version: 1.0.54` in `brave://components`. But if this is still problematic after verifying the new resources library version please let me know.

**Comment by kardusenor** [comment]
> @axeldaniel @robd003 @n33pm this is more of an issue with Brave Browser than adblock-rust, but FWIW it should have been fixed by a component update (`Brave Ad Block Resources Library - Version: 1.0.54` in `brave://components`. But if this is still problematic after verifying the new resources library version please let me know.

Now it happened again
