### ISSUE TITLE
How to update the data directory?

### ISSUE THREAD

**Issue by astuanax** [brave/adblock-rust#311]
Hi, 

I am not sure if this is the right place to ask, but since I am unable to find the answer, I am hoping I can get some answers here. 

The data directory has a number of outdated files, and I could find some script here and there that seem to update DAT files for the adblock extension, but I cannot find a script to update the data directory with all the files that are in there. 

Is there such a script, repo, or other means that is managed by someone?
If not this might be a good idea to set  up a repo with daily automatic updates specifically for adblock-rust users (as opposed to the extension or browser users).

Thx in advance,
Len

**Comment by antonok-edm** [comment]
Hi @astuanax,

I'm not 100% sure what you're trying to achieve, but hopefully something here might be useful for you:

> update DAT files for the adblock extension

Brave Browser has moved away from using DAT files as of [this PR](https://github.com/brave/brave-core/pull/15077) (1.46.x). Rationale for the change is [here](https://github.com/brave/brave-browser/issues/25363). If you still have leftover component directories with adblock `.dat` files in your browser's profile directory, they can be safely removed.

The newer components have a `list.txt` file instead. You can find the full mapping from component IDs to components [here](https://github.com/brave/adblock-resources/blob/master/filter_lists/list_catalog.json). Refer to the `list_text_component.component_id` for each list, _not_ the top-level `component_id`.

> a script to update the data directory with all the files that are in there

You can take a look at [brave-core-crx-packager](https://github.com/brave/brave-core-crx-packager), which is Brave's serverside component packager. In particular, [this section](https://github.com/brave/brave-core-crx-packager#component-extensions) explains how to generate the adblock components, which will then be located in the `build` directory organized by component ID (newer list-based components) or UUID (older DAT-format components).

We still build the older DAT-format components for Brave iOS, which is migrating to the newer list-format components soon™. If you really need those for some reason they will also be located in the `build` directory. But I strongly recommend loading directly from the list format instead.

> The data directory

It occurred to me that you might also be referring to [this](https://github.com/brave/adblock-rust/tree/master/data) data directory. In that case, there isn't any provision for automatic updates; it's considered more of a regression test suite. I'd prefer not to regularly check filter lists into this repo since it would significantly bloat the git history relative to the volume of actual code changes.

We do have a few ["live" tests](https://github.com/brave/adblock-rust/blob/master/tests/live.rs) which run in the CI on this repository and download some of the lists directly at test-time, although they are not extremely comprehensive. If you have ideas of how to make those more useful, I'm certainly open to suggestions!

**Comment by astuanax** [comment]
Thanks for the amazing update, that totally solved my issue!
