### ISSUE TITLE
YouTube blocks default Brave now

### ISSUE THREAD

**Issue by uNetworkingAB** [brave/adblock-rust#328]
YouTube is now entirely broken by default in Brave since they just upped their detection of adblockers (today)

**Comment by antonok-edm** [comment]
@uNetworkingAB Brave uses the same YouTube filters as uBlock Origin, you can track the filter update progress at https://drhyperion451.github.io/does-uBO-bypass-yt/. Once updated filters exist you should be able to force the browser to fetch them by visiting brave://components and pressing `Check for update` on adblock-related components (or doing a full-restart of the browser).

In the meantime, I've generally not encountered any ads when visiting YouTube in a private window.

I'll close this issue since it's related to filters rather than the adblock engine.

**Comment by uNetworkingAB** [comment]
Thanks, it works now. I briefly saw YouTube block the adblocker. It works now, no ads.
