### ISSUE TITLE
Doesn't block ads on twitch still. But other adblocks do

### ISSUE THREAD

**Issue by tyroticuss** [brave/adblock-rust#98]
I've noticed that twitch ads still show up on brave with shields on. However ublock Origin does block twitch ads. 

Version: Version 1.8.86 Chromium: 81.0.4044.129 (Official Build) unknown (64-bit)

Doesn't block twitch ads on linux and windows.

**Comment by ryanbr** [comment]
We have a ticket for this @tyroticuss https://github.com/brave/brave-browser/issues/9027

If you can test in Brave Nightly, (with ads-trackers = aggressive)

**Comment by antonok-edm** [comment]
I believe this should have been fixed by https://github.com/brave/brave-core/pull/5402, which is in Brave Stable as of 1.9.72. I've tried browsing a few streams and wasn't able to encounter any ads.

@tyroticuss Feel free to leave another report on brave/brave-browser#9027 if you're still running into any after updating.
